// dictionaries
export const FETCH_DICTIONARIES = 'FETCH_DICTIONARIES';
export const FETCH_DICTIONARIES_SUCCESS = 'FETCH_DICTIONARIES_SUCCESS';
export const FETCH_DICTIONARIES_ERROR = 'FETCH_DICTIONARIES_ERROR';

// home
export const FETCH_BEST_RESULTS = 'FETCH_BEST_RESULTS';
export const FETCH_BEST_RESULTS_SUCCESS = 'FETCH_BEST_RESULTS_SUCCESS';
export const FETCH_BEST_RESULTS_ERROR = 'FETCH_BEST_RESULTS_ERROR';

// languages
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';

// results
export const CALCULATE_CURRENT_RESULTS_SUCCESS = 'CALCULATE_CURRENT_RESULTS_SUCCESS';
export const CALCULATE_CURRENT_RESULTS_ERROR = 'ERROR_CALCULATE_CURRENT_RESULTS';
export const FETCH_SAVE_RESULTS = 'FETCH_SAVE_RESULTS';
export const FETCH_SAVE_RESULTS_SUCCESS = 'FETCH_SAVE_RESULTS_SUCCESS';
export const FETCH_SAVE_RESULTS_ERROR = 'FETCH_SAVE_RESULTS_ERROR';

// words
export const FETCH_DICTIONARY_WITH_WORDS = 'FETCH_DICTIONARY_WITH_WORDS';
export const FETCH_DICTIONARY_WITH_WORDS_SUCCESS = 'FETCH_DICTIONARY_WITH_WORDS_SUCCESS';
export const FETCH_DICTIONARY_WITH_WORDS_ERROR = 'FETCH_DICTIONARY_WITH_WORDS_ERROR';

// app
export const STATUS_OK = 'ok';
export const STATUS_ERROR = 'error';
