// dictionaries
export const FETCH_DICTIONARIES = 'FETCH_DICTIONARIES';

// home
export const FETCH_BEST_RESULTS = 'FETCH_BEST_RESULTS';

// languages
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';

// results
export const CALCULATE_CURRENT_RESULTS = 'CALCULATE_CURRENT_RESULTS';
export const CALCULATE_CURRENT_RESULTS_SUCCESS = 'CALCULATE_CURRENT_RESULTS_SUCCESS';
export const CALCULATE_CURRENT_RESULTS_ERROR = 'ERROR_CALCULATE_CURRENT_RESULTS';
export const UPLOAD_RESULT = 'FETCH_SAVE_RESULTS';
export const FETCH_SAVE_RESULTS_SUCCESS = 'FETCH_SAVE_RESULTS_SUCCESS';
export const FETCH_SAVE_RESULTS_ERROR = 'FETCH_SAVE_RESULTS_ERROR';

// words
export const FETCH_DICTIONARY_WITH_WORDS = 'FETCH_DICTIONARY_WITH_WORDS';

// app
export const STATUS_OK = 'ok';
export const STATUS_ERROR = 'error';
