export const FETCH_DICTIONARY_WITH_WORDS = 'FETCH_DICTIONARY_WITH_WORDS';
export const FETCH_DICTIONARY_WITH_WORDS_SUCCESS = 'FETCH_DICTIONARY_WITH_WORDS_SUCCESS';
export const FETCH_DICTIONARY_WITH_WORDS_ERROR = 'FETCH_DICTIONARY_WITH_WORDS_ERROR';
